/**
 * This file defines some simple C functions to make ffi interop easier. The
 * majority of the functions are wrapping some pre-processor define that is
 * critical to PHP internals.
 */

#include <Zend/zend.h>
#include <main/php.h>
#include <sapi/embed/php_embed.h>

sapi_request_info * sg_request_info() {
    return &SG(request_info);
}

void * sg_server_context() {
    return SG(server_context);
}

void sg_set_server_context(void *context) {
    SG(server_context) = context;
}

sapi_headers_struct * sg_sapi_headers() {
    return &SG(sapi_headers);
}

unsigned char sg_headers_sent() {
    return SG(headers_sent);
}

void sg_set_headers_sent(unsigned char is_sent) {
    SG(headers_sent) = is_sent;
}

void zend_tsrmls_cache_update() {
    ZEND_TSRMLS_CACHE_UPDATE();
}

/*
 * Create a wrapper around fopen
 *
 * I tried to use libc, but libc defines FILE different from the php bindings
 * generated by bindgen. Thus, it was easier to wrap this and expose it in Rust
 * via an extern fn definition.
 */
FILE *phprpm_fopen(const char *filename, const char *mode) {
    return fopen(filename, mode);
}
